sudo: false

language: java

jdk: openjdk11

before_deploy:
    - ./gradlew clean
    - ./gradlew jar

deploy:
    provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    on:
        branch: master
        repo: CryDeb/hslu_fs19_swat-prg2
