sudo: false

language: java

jdk: openjdk11

addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: $SONAR_AUTH # encrypted value of your token

before_deploy:
    - ./gradlew clean
    - sonar-scanner
    - ./gradlew jar

deploy:
    provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    prerelease: true
    name: Build $(date +'%d.%m.%Y %R')
    on:
        branch: master
        repo: CryDeb/hslu_fs19_swat-prg2
